### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by suibiandou** [PrinceVictor/MHT#3]
环境：1.ubuntu 20.04
2.git 上最新版本fmt

[ 94%] Linking CXX executable run_track
/usr/bin/ld: run_track: hidden symbol `_ZN3fmt2v86detail9dragonbox10to_decimalIfEENS2_10decimal_fpIT_EES5_' in /usr/local/lib/libfmt.a(format.cc.o) is referenced by DSO
/usr/bin/ld: 最后的链结失败: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/run_track.dir/build.make:95：run_track] 错误 1
make[2]: 离开目录“/home/open_code/MHT/build”
make[1]: *** [CMakeFiles/Makefile2:87：CMakeFiles/run_track.dir/all] 错误 2
make[1]: 离开目录“/home/open_code/MHT/build”
make: *** [Makefile:84：all] 错误 2
make: 离开目录“/home/open_code/MHT/build”

**Comment by PrinceVictor** [comment]
hello, I test on my pc successfully.
Furthermore, I pulled the latest fmt from github and built failed. 
So I pushed a new [commit](https://github.com/PrinceVictor/MHT/commit/b6d0ba57b1ba559b82da16e14bfe72f9faaffba9) fixed it to support latest version of fmt library
